### ISSUE TITLE
Install on Laravel 9 

### ISSUE THREAD

**Issue by iamlasse** [Patrikgrinsvall/laravel-bankid#1]
There are problems coming up in the log when I try to install this with L9

Problem 1
    - Root composer.json requires patrikgrinsvall/laravel-bankid v0.2.0 -> satisfiable by patrikgrinsvall/laravel-bankid[v0.2.0].
    - patrikgrinsvall/laravel-bankid v0.2.0 requires illuminate/contracts ^8.0 -> satisfiable by illuminate/contracts[v8.0.0, ..., 8.x-dev].

**Comment by silentridge** [comment]
Hi! Thank you for this. I'm working on a remake of this package for laravel 9 right now and it will be released in a few weeks time hopefully.

**Comment by Patrikgrinsvall** [comment]
or actually, i saw the changes in your fork and applied them to master, not tested or anything but likley it wont be breaking anything
